### ISSUE TITLE
TypeError: pcst_fast(): incompatible function arguments

### ISSUE THREAD

**Issue by agitter** [fraenkel-lab/OmicsIntegrator2#110]
When testing with a toy example, I received an error related to how `pcst_fast` is called:
```
Traceback (most recent call last):
  File "/miniconda3/envs/oi2/bin/OmicsIntegrator", line 8, in <module>
    sys.exit(main())
  File "/miniconda3/envs/oi2/lib/python3.6/site-packages/OmicsIntegrator/__main__.py", line 78, in main
    vertex_indices, edge_indices = graph.pcsf()
  File "/miniconda3/envs/oi2/lib/python3.6/site-packages/OmicsIntegrator/graph.py", line 296, in pcsf
    vertex_indices, edge_indices = pcst_fast(edges, prizes, costs, root, num_clusters, pruning, verbosity_level)
TypeError: pcst_fast(): incompatible function arguments. The following argument types are supported:
    1. (arg0: numpy.ndarray[int64], arg1: numpy.ndarray[float64], arg2: numpy.ndarray[float64], arg3: int, arg4: int, arg5: str, arg6: int) -> Tuple[numpy.ndarray[int32], numpy.ndarray[int32]]

Invoked with: array([[0, 1],
       [0, 2],
       [1, 3],
       [2, 3],
       [4, 0],
       [4, 3]]), array([1., 0., 0., 1., 0.]), array([8e+19, 8e+19, 8e+19, 8e+19, 6, 6], dtype=object), 4, 1, 'strong', 0
```

Could this be related to incompatible package versions?  I'm running on Linux inside a conda environment with these packages:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
axial                     0.1.10                   pypi_0    pypi
blas                      1.0                    openblas
brotlipy                  0.7.0           py36h27cfd23_1003
ca-certificates           2021.1.19            h06a4308_1
certifi                   2020.12.5        py36h06a4308_0
cffi                      1.14.5           py36h261ae71_0
chardet                   4.0.0           py36h06a4308_1003
cryptography              3.4.6            py36hd23ed53_0
decorator                 4.4.2              pyhd3eb1b0_0
git-lfs                   2.13.2               h06a4308_0
goenrich                  1.7.0                    pypi_0    pypi
idna                      2.10               pyhd3eb1b0_0
jinja2                    2.9.6            py36h489bce4_1
ld_impl_linux-64          2.33.1               h53a641e_7
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libopenblas               0.3.13               h4367d64_0
libstdcxx-ng              9.1.0                hdf63c60_0
markupsafe                1.1.1            py36h7b6447c_0
ncurses                   6.2                  he6710b0_1
networkx                  2.1                      py36_0
numpy                     1.19.2           py36h6163131_0
numpy-base                1.19.2           py36h75fe3a5_0
omicsintegrator           2.3.8                    pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0
pandas                    0.23.4           py36h04863e7_0
patsy                     0.5.1                    py36_0
pcst-fast                 1.0.7                    pypi_0    pypi
pip                       21.0.1           py36h06a4308_0
pybind11                  2.5.0            py36hfd86e86_0
pycparser                 2.20                       py_2
pyopenssl                 20.0.1             pyhd3eb1b0_1
pysocks                   1.7.1            py36h06a4308_0
python                    3.6.13               hdb3f193_0
python-dateutil           2.8.1              pyhd3eb1b0_0
python-louvain            0.11             py36h28b3542_0
pytz                      2021.1             pyhd3eb1b0_0
readline                  8.1                  h27cfd23_0
requests                  2.25.1             pyhd3eb1b0_0
scikit-learn              0.19.2           py36h22eb022_0
scipy                     1.1.0            py36he2b7bc3_2
setuptools                52.0.0           py36h06a4308_0
six                       1.15.0           py36h06a4308_0
sqlite                    3.35.2               hdfb4753_0
statsmodels               0.12.2           py36h27cfd23_0
tk                        8.6.10               hbc83047_0
urllib3                   1.26.4             pyhd3eb1b0_0
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
```

**Comment by alexlenail** [comment]
It could be. I should have pinned numpy versions and whatnot. Is `8e+19` a float64?

I wrote a bunch of tests a long time ago (https://github.com/fraenkel-lab/OmicsIntegrator2/blob/master/test/test_graph.py). Do those still run?

**Comment by agitter** [comment]
For the tests below, I'm now running with the example data to make sure I don't have an error in my edge or prize files
```
OmicsIntegrator -e interactomes/inbiomap.9.12.2016.exp.oi2 -p example/example_prizes.tsv -o .
```

> Is 8e+19 a float64?

No, it doesn't seem to be.  I printed the dtypes before calling pcst_fast:
- edges is int64
- prizes is float64
- costs is object

Working backwards, inside `__init__` `self.edge_costs` has dtype float64.  However, inside `_reset_hyperparameters` `self.costs` has dtype object after line 130.
https://github.com/fraenkel-lab/OmicsIntegrator2/blob/ea1092fe0053556338cf29c4840a1ff35e8a4f81/src/graph.py#L130

The tests in `test_graph.py` all passed.

**Comment by agitter** [comment]
I believe this is happening because the costs are so huge.  For example,
```
>>> a = np.array([1.0, 2.0])
>>> a
array([1., 2.])
>>> a.dtype
dtype('float64')
>>> b = 10**20 * a
>>> b
array([1e+20, 2e+20], dtype=object)
```

Why are the edge penalties multiplied by `(10**self.params.g)`?
https://github.com/fraenkel-lab/OmicsIntegrator2/blob/ea1092fe0053556338cf29c4840a1ff35e8a4f81/src/graph.py#L127-L128

**Comment by alexlenail** [comment]
> Why are the edge penalties multiplied by (10**self.params.g)?

gamma, or g, is a parameter which penalizes "hub nodes". It is log-scaled, so g = 5 means penalty = 1e5. Although I had thought that was well-documented, I can't find a trace of it in the [docs](https://fraenkel-lab.github.io/OmicsIntegrator2/html/index.html), which is disappointing. 

> inside __init__ self.edge_costs has dtype float64. However, inside _reset_hyperparameters self.costs has dtype object after line 130.

Thanks for tracking that down. Let's raise an issue about this. 

> For the tests below, I'm now running with the example data to make sure I don't have an error in my edge or prize files

> The tests in test_graph.py all passed.

Does this mean you're able to run OI2 successfully now? 

cc @iamjli

**Comment by agitter** [comment]
> Does this mean you're able to run OI2 successfully now?

No, I'm still stuck with the same pcst_fast TypeError.  Because the test cases pass in my conda environment, I now suspect that it could have something to do with how I'm running OI2 via the command line interface.  The default value of g in `__main__.py` is 20, which is fairly large.

Are you able to run
```
OmicsIntegrator -e interactomes/inbiomap.9.12.2016.exp.oi2 -p example/example_prizes.tsv -o .
```
from the command line successfully?

**Comment by alexlenail** [comment]
> something to do with how I'm running OI2 via the command line interface

Back when I was in the fraenkel lab, we ran OI2 via jupyter notebooks (there should be some examples in the repo). The CLI interface seems outdated (e.g. g = 20 is much too large). A current member of the lab should definitely help you bring it up to date.

**Comment by agitter** [comment]
I lowered the default g from 20 to 1, and the pcst_fast TypeError went away.  Preventing this error could involve:
- Updating `_check_validity_of_hyperparameters` to set a maximum value of g
- Updating `_check_validity_of_instance` to [test the dtype](https://stackoverflow.com/questions/26921836/correct-way-to-test-for-numpy-dtype/26921882) of the edges, prizes, and costs.

> A current member of the lab should definitely help you bring it up to date.

I'm willing to submit minor pull requests to fix bugs and make it suitable for my use case, but it would be great to have a current lab member guide me so I can make changes you would want to merge.

**Comment by agitter** [comment]
After more testing, the issue does not seem to be only due to the magnitude of g.  I could reproduce the error with g = 20, but it works when g = 20.0.  There may be a numeric issue.  Casting g to be a float has fixed this error so far for me.
