### ISSUE TITLE
Randomizations: OverflowError: int too large to convert to float

### ISSUE THREAD

**Issue by matthewfallan** [fraenkel-lab/OmicsIntegrator2#92]
`example/OI2_pipeline.ipynb` no longer runs properly. `grid_search` gives this error: 

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/mfa/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/mfa/miniconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "../src/graph.py", line 526, in _eval_PCSF_runs
    self._reset_hyperparameters(params=params)
  File "../src/graph.py", line 128, in _reset_hyperparameters
    ((N - self.node_degrees[a] - 1) * (N - self.node_degrees[b] - 1) + self.node_degrees[a] * self.node_degrees[b]) for a, b in self.edges])
OverflowError: int too large to convert to float
"""

The above exception was the direct cause of the following exception:

OverflowError                             Traceback (most recent call last)
<ipython-input-20-067b42e3a683> in <module>()
----> 1 results = graph.grid_search(prize_file, Ws, Bs, Gs)

~/lib/OmicsIntegrator2/src/graph.py in grid_search(self, prize_file, Ws, Bs, Gs)
    580         """
    581 
--> 582         return self.grid_randomization(prize_file, Ws, Bs, Gs, 0, 0)
    583 
    584 

~/lib/OmicsIntegrator2/src/graph.py in grid_randomization(self, prize_file, Ws, Bs, Gs, noisy_edges_reps, random_terminals_reps)
    557         param_sets = [{'w': w, 'b': b, 'g': g, 'noisy_edge_reps': noisy_edges_reps, 'random_terminals_reps': random_terminals_reps} for (w, b, g) in product(Ws, Bs, Gs)]
    558 
--> 559         results = pool.map(self._eval_PCSF_runs, param_sets)
    560         # Convert to dictionary format
    561         results = {paramstring: {"forest": forest, "augmented_forest": augmented_forest} for paramstring, forest, augmented_forest in results }

~/miniconda3/lib/python3.6/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    264         in a list that is returned.
    265         '''
--> 266         return self._map_async(func, iterable, mapstar, chunksize).get()
    267 
    268     def starmap(self, func, iterable, chunksize=None):

~/miniconda3/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

OverflowError: int too large to convert to float
```

**Comment by iamjli** [comment]
Interactome file:
[iRefIndex_v14_MIScore_interactome_C9.costs.txt](https://github.com/fraenkel-lab/OmicsIntegrator2/files/2246789/iRefIndex_v14_MIScore_interactome_C9.costs.txt)

Prize file: 
[protein_TF_prizes.txt](https://github.com/fraenkel-lab/OmicsIntegrator2/files/2246792/protein_TF_prizes.txt)

**Comment by zfrenchee** [comment]
@iamjli @matthewfallan   `example/Example_Usage.ipynb` works on master, and the tests run, so I've changed the title of this issue. 

It seems like there's integer overflow during computation of the edge penalty formula, modulated by `graph.params.g` i.e. gamma. What was the value of gamma that caused this bug? 

Recall that in OmicsIntegrator2.2, gamma is on a log scale, as you requested @iamjli. You should be trying values of gamma between 1 and 10 now, rather than 1 and 1,000,000,000.

**Comment by zfrenchee** [comment]
@iamjli if that turns out to be the issue, please close this issue.

**Comment by iamjli** [comment]
@matthewfallan could you check this please?

**Comment by zfrenchee** [comment]
@matthewfallan @iamjli closing this issue as stale.
